// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHHBWj3m3Vqu7JSBFtwsGK3Vkqvzi7ql4',
    appId: '1:755621754216:web:05800a84c10ec97fe412dd',
    messagingSenderId: '755621754216',
    projectId: 'flutter-auth-38a8c',
    authDomain: 'flutter-auth-38a8c.firebaseapp.com',
    storageBucket: 'flutter-auth-38a8c.firebasestorage.app',
    measurementId: 'G-T65WHERN48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFfd-eQyw5FyyZTXgZXAoWKXqcwKt5wP0',
    appId: '1:755621754216:android:6b439ef2a717c281e412dd',
    messagingSenderId: '755621754216',
    projectId: 'flutter-auth-38a8c',
    storageBucket: 'flutter-auth-38a8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHHEE1Qt0IXouvtmXvEycmiAirnmDgpMc',
    appId: '1:755621754216:ios:f0976c036b4daae8e412dd',
    messagingSenderId: '755621754216',
    projectId: 'flutter-auth-38a8c',
    storageBucket: 'flutter-auth-38a8c.firebasestorage.app',
    androidClientId: '755621754216-6hauqimtrdodk6gad3s40o8ssisor638.apps.googleusercontent.com',
    iosClientId: '755621754216-s4m6dmabl37ognkul9ofig06ikn5od89.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHHEE1Qt0IXouvtmXvEycmiAirnmDgpMc',
    appId: '1:755621754216:ios:f0976c036b4daae8e412dd',
    messagingSenderId: '755621754216',
    projectId: 'flutter-auth-38a8c',
    storageBucket: 'flutter-auth-38a8c.firebasestorage.app',
    androidClientId: '755621754216-6hauqimtrdodk6gad3s40o8ssisor638.apps.googleusercontent.com',
    iosClientId: '755621754216-s4m6dmabl37ognkul9ofig06ikn5od89.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHHBWj3m3Vqu7JSBFtwsGK3Vkqvzi7ql4',
    appId: '1:755621754216:web:c6d45049d527ecabe412dd',
    messagingSenderId: '755621754216',
    projectId: 'flutter-auth-38a8c',
    authDomain: 'flutter-auth-38a8c.firebaseapp.com',
    storageBucket: 'flutter-auth-38a8c.firebasestorage.app',
    measurementId: 'G-9VVQVZ8GV0',
  );
}
